### ISSUE TITLE
0.5.0

### ISSUE THREAD

**Issue by FrederikBarkholt** [isdsucph/isds2022#25]
<img width="443" alt="Skærmbillede 2022-07-27 kl  13 50 26" src="https://user-images.githubusercontent.com/109417312/181242901-b63ed263-ccf4-42e6-a0ae-91435fd49d12.png">

What am I doing wrong in the ex. and how can I fix it?:)

**Comment by isdsucph** [comment]
Hi @FrederikBarkholt 

You need to indent the line 
```python
answer_050.append(new_element)
```
Furthermore, you should apply your function `change_url` to each `x` in the list `chars2` instead of `chars2` as a whole. 

Cheers 
Jonas
