### ISSUE TITLE
Lost acces to weather data

### ISSUE THREAD

**Issue by Frejafalk** [isdsucph/isds2022#8]
We can't acces the weather data today. It was running fine yesterday, but now we get the message "You don't have permission to access /pub/data/ghcn/daily/by_year/1860.csv.gz on this server.", so we can't run our codes in the last task, because it can't acces the datafiles - can you help?

**Comment by isdsucph** [comment]
Hi @Frejafalk 

This might be the after effects of their maintenance. 
![image](https://user-images.githubusercontent.com/86770179/179185807-eaad3ead-885b-4638-b67f-ff03fc04a87f.png)
If it is still not working tonight, we'll come up with a way to sidestep this problem. 

Cheers
Jonas

**Comment by isdsucph** [comment]
As also written in #11, it should be working now :)
